### ISSUE TITLE
Initial Task List (data-ify typescript config options)

### ISSUE THREAD

**Issue by Ethan-Arrowood** [MatterhornDev/tsconfig-helper#1]
I imagine the simplest way to do this is using a JSON object. Forward-thinking with potential use cases of this utility include both a command line interface and a graphical user interface. Regardless of the interface, the output is going to be a `tsconfig.json` file (or a `.js` or `package.json`).

- [ ] Copy all tsconfig rules to a `rules.json` file. Should be structured something like so:
```json
{
  "rule": {
    "shortDesc": "",
    "longDesc": "",
    "type": "string | boolean | etc",
    "enumVals": []
  }, 
  "nextRule": { }
}
```
- [ ] Write up documentation on what the file is and how it is used. Talk about the typescript compiler and other ways to use it (like passing rules as command line arguments)
- [ ] Conversational CLI that allows the user to interact with our data and learn about the various properties
- [ ] Basic API that would return the requested rule (use queryparams and get requests)
- [ ] Design an user interface that allows the user to select rules and quickly view quick or verbose information on each of them. Should have examples.

**Comment by Ethan-Arrowood** [comment]
All compiler options are found in this md file: https://github.com/microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md

Could be easy to write a script to parse this into json automatically 🤔
